---
- name: Configure EKS Worker Nodes
  hosts: eks_nodes
  become: yes
  
  tasks:
    - name: Update all packages
      yum:
        name: '*'
        state: latest
        update_only: yes
      
    - name: Install required packages
      yum:
        name:
          - docker
          - git
          - jq
          - python3
          - python3-pip
        state: present
      
    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
      
    - name: Install AWS CLI
      pip:
        name: awscli
        executable: pip3
        state: present
      
    - name: Install kubectl
      get_url:
        url: https://storage.googleapis.com/kubernetes-release/release/v1.23.6/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
      
    - name: Create .kube directory
      file:
        path: /home/ec2-user/.kube
        state: directory
        owner: ec2-user
        group: ec2-user
        mode: '0755'
      
    - name: Configure kubelet service
      copy:
        content: |
          [Service]
          Environment="KUBELET_EXTRA_ARGS=--node-labels=node.kubernetes.io/worker=true"
        dest: /etc/systemd/system/kubelet.service.d/20-worker-labels.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart kubelet
  
  handlers:
    - name: Restart kubelet
      systemd:
        name: kubelet
        state: restarted
        daemon_reload: yes