version: 0.2

env:
  variables:
    CHART_PATH: standardized-path/app

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - terraform version
      - helm version
  build:
    commands:
      - terraform -chdir=infra init -backend=false
      - terraform -chdir=infra fmt -check
      - terraform -chdir=infra validate
      - helm lint ${CHART_PATH} -f platform/apps/dev/values.yaml
      - helm lint ${CHART_PATH} -f platform/apps/stage/values.yaml
      - helm lint ${CHART_PATH} -f platform/apps/prod/values.yaml
      - helm template simple-app-dev ${CHART_PATH} -f platform/apps/dev/values.yaml > /tmp/simple-app-dev.yaml
      - helm template simple-app-stage ${CHART_PATH} -f platform/apps/stage/values.yaml > /tmp/simple-app-stage.yaml
      - helm template simple-app-prod ${CHART_PATH} -f platform/apps/prod/values.yaml > /tmp/simple-app-prod.yaml
