{{- with .Values.externalSecret }}
{{- if .enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "app.fullname" $ }}
  labels:
    {{- include "app.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    name: {{ .store.name }}
    kind: {{ .store.kind }}
  target:
    name: {{ include "app.fullname" $ }}
    creationPolicy: Owner
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- with .remoteRef.property }}
        property: {{ . }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
