apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: environments
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            app: simple-app
            valuesPath: platform/apps/dev/values.yaml
          - env: stage
            app: simple-app
            valuesPath: platform/apps/stage/values.yaml
          - env: prod
            app: simple-app
            valuesPath: platform/apps/prod/values.yaml
          - env: dev
            app: app-b
            valuesPath: platform/apps/app-b/dev/values.yaml
          - env: stage
            app: app-b
            valuesPath: platform/apps/app-b/stage/values.yaml
          - env: prod
            app: app-b
            valuesPath: platform/apps/app-b/prod/values.yaml
   template:
    metadata:
      name: "{{app}}-{{env}}"
      labels:
        app: "{{app}}"
        environment: "{{env}}"
    spec:
      project: tenant-apps
      source:
        repoURL: https://github.com/tukue/simpleAppInfraCode.git
        targetRevision: main
        path: standardized-path/app
        helm:
          valueFiles:
            - "/{{valuesPath}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{env}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
