replicaCount: 2

image:
  repository: ${{ imageRepo }}/${{ appName }}
  tag: "1.0.0-rc1"

ingress:
  enabled: true
  hosts:
    - host: ${{ appName }}-stage.example.com
      paths:
        - path: /
          pathType: Prefix

env:
  - name: ENVIRONMENT
    value: "stage"
  - name: PORT
    value: "${{ port }}"

externalSecret:
  enabled: true
  data:
    - secretKey: db-password
      remoteRef:
        key: stage/${{ appName }}/db-password
