apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app-prod
  namespace: argocd
  labels:
    app: simple-app
    environment: prod
spec:
  project: tenant-apps
  source:
    repoURL: https://github.com/tukue/simpleAppInfraCode.git
    targetRevision: main
    path: standardized-path/app
    helm:
      valueFiles:
        - ../../platform/apps/prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
