replicaCount: 1

image:
  repository: ${{ imageRepo }}/${{ appName }}
  tag: "1.0.0-dev.1"

ingress:
  enabled: true
  hosts:
    - host: ${{ appName }}-dev.example.com
      paths:
        - path: /
          pathType: Prefix

env:
  - name: ENVIRONMENT
    value: "dev"
  - name: PORT
    value: "${{ port }}"

externalSecret:
  enabled: true
  data:
    - secretKey: db-password
      remoteRef:
        key: dev/${{ appName }}/db-password
