replicaCount: 1

image:
  repository: ${{ parameters.imageRepo }}${{ parameters.appName }}
  tag: "1.0.0-dev.1"

ingress:
  enabled: true
  hosts:
    - host: ${{ parameters.appName }}-dev.example.com
      paths:
        - path: /
          pathType: Prefix

env:
  - name: ENVIRONMENT
    value: "dev"
  - name: PORT
    value: "${{ parameters.port }}"

externalSecret:
  enabled: true
  data:
    - secretKey: db-password
      remoteRef:
        key: dev/${{ parameters.appName }}/db-password
