replicaCount: 1

image:
  tag: "1.0.0-dev.1"

env:
  - name: ENVIRONMENT
    value: "dev"
  - name: MESSAGE
    value: "Hello from the dev platform"
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: simple-app-dev
        key: db-password

externalSecret:
  enabled: true
  data:
    - secretKey: db-password
      remoteRef:
        key: dev/simple-app/db-password
